services:
  paperless.frontend:
      image: paperlessfrontend
      build:
        context: ./frontend
        dockerfile: Dockerfile
      container_name: paperless_frontend
      ports:
        - "8080:80"
      environment:
        - REACT_APP_API_BASE_URL=http://paperless.rest:8080
      depends_on:
        - paperless.rest
      networks:
        - paperless_network
      restart: on-failure
      labels:
        - "com.microsoft.visualstudio.debuggee=true"

  postgres:
    image: postgres:16
    container_name: paperless_postgres
    environment:
      POSTGRES_DB: dmsdb
      POSTGRES_USER: dms
      POSTGRES_PASSWORD: dms123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - paperless_network
    healthcheck:                                    
      test: ["CMD-SHELL", "pg_isready -U dms -d dmsdb"]
      interval: 5s
      timeout: 5s
      retries: 5

  paperless.rest:
    image: ${DOCKER_REGISTRY-}paperlessrest
    build:
      context: .
      dockerfile: Paperless.REST/Dockerfile
    container_name: paperless_rest
    ports:
      - "8081:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DMSDb=Host=postgres;Port=5432;Database=dmsdb;Username=dms;Password=dms123
    depends_on:
      rabbitmq:
        condition: service_started
      postgres:
        condition: service_healthy                  
    networks:
      - paperless_network
    restart: on-failure 
    
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"  
      - "9093:15672" 
    networks:
      - paperless_network

  paperless_ocrworker:
    build:
      context: .
      dockerfile: Paperless.OcrWorker/Dockerfile
    container_name: paperless_ocrworker
    ports:
      - "8082:8082"
    environment:
      - RABBITMQ_HOST=rabbitmq
    depends_on:
      - rabbitmq
    networks:
      - paperless_network

volumes:
  postgres_data:

networks:
  paperless_network:
    driver: bridge