services:

  paperless.frontend:
    image: paperlessfrontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: paperless_frontend
    ports:
      - "8080:80"
    environment:
      - REACT_APP_API_BASE_URL=http://paperless.rest:8080
    depends_on:
      paperless.rest:
        condition: service_started
    networks:
      - paperless_network
    restart: on-failure

  postgres:
    image: postgres:16
    container_name: paperless_postgres
    environment:
      POSTGRES_DB: dmsdb
      POSTGRES_USER: dms
      POSTGRES_PASSWORD: dms123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - paperless_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dms -d dmsdb"]
      interval: 5s
      timeout: 5s
      retries: 5

  paperless.rest:
    image: ${DOCKER_REGISTRY-}paperlessrest
    build:
      context: .
      dockerfile: Paperless.REST/Dockerfile
    container_name: paperless_rest
    ports:
      - "8081:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DMSDb=Host=postgres;Port=5432;Database=dmsdb;Username=dms;Password=dms123
      - RabbitMQ__Host=rabbitmq
      - RabbitMQ__Port=5672
      - RabbitMQ__User=guest
      - RabbitMQ__Password=guest
      - RabbitMQ__QueueName=ocr_queue
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_healthy
      minio:
        condition: service_started
    networks:
      - paperless_network
    restart: on-failure

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "9093:15672"
    networks:
      - paperless_network
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 5s
      retries: 10

  paperless_ocrworker:
    build:
      context: .
      dockerfile: Paperless.OcrWorker/Dockerfile
    container_name: paperless_ocrworker
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_QUEUE=ocr_queue
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_BUCKET=documents
      - GENAI_QUEUE=genai_queue
      - INDEXING_QUEUE=indexing_queue
      - ELASTIC_URL=http://elasticsearch:9200
    depends_on:
      rabbitmq:
        condition: service_healthy
      minio:
        condition: service_started
    networks:
      - paperless_network

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9090:9090"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9090"
    networks:
      - paperless_network

  paperless.genaiworker:
    build:
        context: .                     
        dockerfile: Paperless.GenAIWorker/Dockerfile
    container_name: paperless_genaiworker
    environment:
      - RABBITMQ_HOST=rabbitmq
      - GENAI_QUEUE=genai_queue
      - REST_BASE_URL=http://paperless.rest:8080
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - GEMINI_MODEL=${GEMINI_MODEL}
    depends_on:
      rabbitmq:
        condition: service_started
      paperless.rest:
        condition: service_started
    networks:
      - paperless_network
    restart: on-failure

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    container_name: paperless_elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    networks:
      - paperless_network

  paperless_batch:
   build:
    context: .
    dockerfile: Paperless.BatchProcess/Dockerfile
   depends_on:
    postgres:
      condition: service_healthy
   volumes:
    - ./accesslogs:/data/accesslogs
   networks:
    - paperless_network

volumes:
  postgres_data:

networks:
  paperless_network:
    driver: bridge
