<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Elastic.Clients.Elasticsearch" Version="8.12.0-preview.2" />
    <PackageReference Include="Ghostscript.NET" Version="1.3.1" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.22.1" />
    <PackageReference Include="Minio" Version="7.0.0" />
    <PackageReference Include="RabbitMQ.Client" Version="7.2.0" />
    <PackageReference Include="Tesseract" Version="5.2.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="tessdata\script\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Paperless.Models\Paperless.Models.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="tessdata\eng.traineddata">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
